url:
  rails_home_url: "https://rubyonrails.org/"
  rails_tutorial_url: "https://www.railstutorial.org/"
  rails_help_url: "https://www.railstutorial.org/help"
  rails_book_url: "https://www.railstutorial.org/book"
  rails_contact_url: "https://www.railstutorial.org/contact"
  rails_news_url: "https://news.learnenough.com/"
  rails_screencasts_url: "https://screencasts.railstutorial.org/"
  learn_enough_url: "https://www.learnenough.com/"
  author_url: "https://www.michaelhartl.com/"
validates:
  name_max_length: 50
  password_min_length: 6
  email_max_length: 255
  email_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
